POST http://localhost:3001/api/user HTTP/1.1
content-type: application/json 

{
  "email": "bakoukeita@gmail.com",
  "password": "bakou",
  "firstname": "B",
  "minit": "",
  "lastname": "keita"
}

 
###
POST http://localhost:3001/api/sale HTTP/1.1
content-type: application/json
 
 {
  "description": "Apple",
  "qty": 2,
  "price": 200,
  "Total": 400,
  "userId": "636ec3fcd30691464e1a7c06"
 }